#!/bin/bash
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
sudo yum update
sudo yum install java-21-amazon-corretto-headless
sudo yum install java-21-amazon-corretto
sudo yum install jenkins -y
sudo systemctl start jenkins 
sudo systemctl enable jenkins
sudo yum install firewalld -y
sudo systemctl start firewalld 
sudo systemctl enable firewalld 
firewall-cmd --zone=public --add-port=8080/tcp --permanent
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
yum install git -y
